# Generated by Django 3.0.5 on 2020-05-27 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('earth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='randevu',
            fields=[
                ('rId', models.AutoField(primary_key=True, serialize=False)),
                ('aTuru', models.TextField(db_column='Atık Türü', max_length=50, verbose_name='Atık Türü')),
                ('rTarih', models.DateField(db_column='Tarih', verbose_name='Tarih')),
                ('rSaat', models.TimeField(db_column='Saat', verbose_name='Saat')),
                ('fId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='earth.firma')),
                ('kId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='earth.kullanici')),
            ],
        ),
    ]
