# Generated by Django 3.0.5 on 2020-05-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earth', '0002_randevu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='randevu',
            name='kId',
        ),
        migrations.AlterField(
            model_name='firma',
            name='fAdi',
            field=models.CharField(db_column='Adı', max_length=200, verbose_name='Adı'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='fAdres',
            field=models.CharField(db_column='Adres', max_length=400, verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='fTel',
            field=models.CharField(db_column='Telefon', max_length=20, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='randevu',
            name='aTuru',
            field=models.CharField(db_column='Atık Türü', max_length=50, verbose_name='Atık Türü'),
        ),
        migrations.DeleteModel(
            name='kullanici',
        ),
    ]
