# Generated by Django 3.0.5 on 2020-05-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earth', '0003_auto_20200528_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='kullanici',
            fields=[
                ('kId', models.AutoField(primary_key=True, serialize=False)),
                ('kAdi', models.CharField(db_column='Adı', max_length=100, verbose_name='Adı')),
                ('kSoyadi', models.CharField(db_column='Soyadı', max_length=100, verbose_name='Soyadı')),
                ('kTel', models.CharField(db_column='Telefon', max_length=20, verbose_name='Telefon')),
                ('keMail', models.EmailField(db_column='Email', max_length=254, verbose_name='E-Mail')),
                ('ktc', models.CharField(db_column='T.C.', max_length=11, verbose_name='T.C.')),
                ('kimage', models.FileField(blank=True, null=True, upload_to='')),
                ('ksehir', models.CharField(db_column='Şehir', max_length=400, verbose_name='Şehir')),
                ('kilce', models.CharField(db_column='İlçe', max_length=100, verbose_name='İlçe')),
                ('kmahalle', models.CharField(db_column='Mahalle', max_length=100, verbose_name='Mahalle')),
                ('ksokak', models.CharField(db_column='Sokak', max_length=100, verbose_name='Sokak')),
                ('kno', models.CharField(db_column='No', max_length=50, verbose_name='No')),
                ('kullaniciA', models.CharField(db_column='Kullanıcı Adı', max_length=50, verbose_name='Kullanıcı Adı')),
                ('kullaniciS', models.CharField(db_column='Şifre', max_length=50, verbose_name='Şifre')),
                ('kullaniciTS', models.CharField(db_column='Tekrar Şifre', max_length=50, verbose_name='Tekrar Şifre')),
            ],
        ),
    ]
