# Generated by Django 3.0.5 on 2020-05-28 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('earth', '0004_kullanici'),
    ]

    operations = [
        migrations.DeleteModel(
            name='randevu',
        ),
    ]
