# Generated by Django 3.0.5 on 2020-05-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earth', '0006_randevu'),
    ]

    operations = [
        migrations.AddField(
            model_name='randevu',
            name='aciklama',
            field=models.CharField(db_column='Açıklama', max_length=100, null=True, verbose_name='Açıklama'),
        ),
    ]
